#ifndef ERROR_H
#define ERROR_H

typedef enum {
  STATUS_OK,
  STATUS_CONFIG_MISSING_VALUE,
  STATUS_CONFIG_INVALID_VALUE,
  STATUS_MENU_FILE_NOT_FOUND,
  STATUS_RESOURCES_FILE_NOT_FOUND,
  STATUS_INVALID_ORDER,
  STATUS_RESOURCE_UNAVAILABLE,
  STATUS_INVALID_PARAMETER,
} ErrorStatus;

#endif
