services:
  workspace:
    # build: .
    entrypoint: sleep infinity
    image: git.zarantonello.dev/university/os-group-5:ci@sha256:2f25249a4bb3651cbb97d20b7f08532c743f26213e227b0e782304fe9be1dd0b
    volumes:
      - ..:/workspace:z,cached
    working_dir: /workspace
