services:
  workspace:
    # build: .
    entrypoint: sleep infinity
    image: git.zarantonello.dev/university/os-group-5:ci@sha256:0fb19ff4e66b5b64b42393cec1fbc0979b2aaefff7994ad4fa0d89fd578c4f0d
    volumes:
      - ..:/workspace:z,cached
    working_dir: /workspace
