services:
  workspace:
    # build: .
    entrypoint: sleep infinity
    image: git.zarantonello.dev/university/os-group-5:ci@sha256:f76ca16dae2e6029c8442e491bbc2b791c9fcc665b7c03d48a575c4ab98de247
    volumes:
      - ..:/workspace:z,cached
    working_dir: /workspace
