concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check-yamllint:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v6.0.2
      - name: Build
        run: CC=clang make build
      - name: Clang tidy
        run: make clang-tidy/check
      - name: Clang format
        run: make clang-format/check

"on":
  pull_request:
    branches:
      - main
