concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Build
        run: CC=clang make build -j $(nproc)
      - name: Clang tidy
        run: make clang-tidy/check
      - name: Clang format
        run: make clang-format/check

"on":
  pull_request:
    branches:
      - main
