concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build
        run: CC=clang make build -j $(nproc)
      - name: Clang tidy
        run: make clang-tidy/check
      - name: Clang format
        run: make clang-format/check

"on":
  pull_request:
    branches:
      - main
